// Generated by scripts/fetch-vault-abi.sh from the verified source of 0x7005abfBb48C4878d671A99bE7C9b1d204CD4364 on Arbitrum One.
export const pythOracleAbi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "priceFeedId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "staleAfter",
            type: "uint256",
          },
          {
            internalType: "contract IPyth",
            name: "pythContract",
            type: "address",
          },
        ],
        internalType: "struct PythOracleConfig",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "signedCoefficient",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "exponent",
        type: "int256",
      },
    ],
    name: "CoefficientOverflow",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "signedCoefficient",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "exponent",
        type: "int256",
      },
    ],
    name: "ExponentOverflow",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "signedCoefficient",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "exponent",
        type: "int256",
      },
    ],
    name: "NegativeFixedDecimalConversion",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
    ],
    name: "NonPositivePrice",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "priceFeedId",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "staleAfter",
            type: "uint256",
          },
          {
            internalType: "contract IPyth",
            name: "pythContract",
            type: "address",
          },
        ],
        indexed: false,
        internalType: "struct PythOracleConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "Construction",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "I_PRICE_FEED_ID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "I_PYTH_CONTRACT",
    outputs: [
      {
        internalType: "contract IPyth",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "I_STALE_AFTER",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;
