#!/usr/bin/env bash
# Run inside the nix dev shell (`nix develop -c npm run abi`). Writes the committed
# ABIs under src/lib/contracts/ from their verified sources:
# - the CycloVault implementation cyclo.sol pins as PROD_FLARE_CYCLO_VAULT_IMPLEMENTATION_V2 (Flare)
# - the PythOracle cyclo.sol pins as PROD_PYTH_ORACLE_WETH_USD_ARBITRUM (Arbitrum One)
# - IPyth from the Pyth Solidity SDK package the oracles were built against
set -euo pipefail
DIR="$(cd "$(dirname "$0")/.." && pwd)/src/lib/contracts"
write() { # <name> <provenance> <abi json on stdin>
  { echo "// Generated by scripts/fetch-vault-abi.sh from $2."; echo "export const $1 = $(jq .) as const;"; } > "$DIR/$1.ts"
  echo "wrote $DIR/$1.ts"
}
VAULT=0xb04c8CA7127997F8832152112a00Cd37Dc3F49E9
curl -sf "https://flare-explorer.flare.network/api?module=contract&action=getabi&address=$VAULT" | jq -e -r '.result' \
  | write erc20PriceOracleReceiptVaultAbi "the verified source of $VAULT on Flare"
ORACLE=0x7005abfBb48C4878d671A99bE7C9b1d204CD4364
curl -sf "https://arbitrum.blockscout.com/api?module=contract&action=getabi&address=$ORACLE" | jq -e -r '.result' \
  | write pythOracleAbi "the verified source of $ORACLE on Arbitrum One"
PYTH_SDK=4.3.1
curl -sfL "https://unpkg.com/@pythnetwork/pyth-sdk-solidity@$PYTH_SDK/abis/IPyth.json" \
  | write iPythAbi "@pythnetwork/pyth-sdk-solidity@$PYTH_SDK abis/IPyth.json"
prettier --write "$DIR"/erc20PriceOracleReceiptVaultAbi.ts "$DIR"/pythOracleAbi.ts "$DIR"/iPythAbi.ts >/dev/null
