#!/usr/bin/env bash
# Writes src/lib/contracts/erc20PriceOracleReceiptVaultAbi.ts from the verified
# source of cyclo.sol's PROD_FLARE_CYCLO_VAULT_IMPLEMENTATION_V2 on Flare.
set -euo pipefail
IMPLEMENTATION=0xb04c8CA7127997F8832152112a00Cd37Dc3F49E9
OUT="$(cd "$(dirname "$0")/.." && pwd)/src/lib/contracts/erc20PriceOracleReceiptVaultAbi.ts"
ABI=$(curl -sf "https://flare-explorer.flare.network/api?module=contract&action=getabi&address=$IMPLEMENTATION" | jq -e -r '.result')
{
  echo "// Generated by scripts/fetch-vault-abi.sh from the verified source of $IMPLEMENTATION on Flare."
  echo "export const erc20PriceOracleReceiptVaultAbi = $(printf '%s' "$ABI" | jq .) as const;"
} > "$OUT"
echo "wrote $OUT"
