name: NPM Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: ./prep-sushi.sh
      - run: nix develop -c npm i
        working-directory: ./cyclo.sol
      - run: nix develop -c forge build
        working-directory: ./cyclo.sol
      - run: nix develop -c npm run codegen
      - run: nix develop -c npm run graphql-codegen
      - run: nix develop -c npm run test
        env:
          PUBLIC_WALLETCONNECT_ID: ${{ secrets.PUBLIC_WALLETCONNECT_ID }}
          PUBLIC_LAUNCHED: ${{ vars.PUBLIC_LAUNCHED }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: ./prep-sushi.sh
      - run: nix develop -c npm i
        working-directory: ./cyclo.sol
      - run: nix develop -c forge build
        working-directory: ./cyclo.sol
      - run: nix develop -c npm run codegen
      - run: nix develop -c npm run graphql-codegen
      - run: nix develop -c npm run svelte-lint-format-check
        env:
          PUBLIC_WALLETCONNECT_ID: ${{ secrets.PUBLIC_WALLETCONNECT_ID }}
          PUBLIC_LAUNCHED: ${{ vars.PUBLIC_LAUNCHED }}
